language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 120s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: pLA84Ndbg2U9065/BBjqH/CyH4//y50fLcLxy79dqCUKuAtges4JUUidvQIcv6au1IfDj+oN1WJ3LokhKypX8RE4Uc2rEt9m2zh0IJhZRCanc1Cy2SJHJTSPsxTOa8o4cA1h2ION2cX2vyWBwUcdPefGDfJX1zMu1fgwaX3FqkBcXAurWhk6/hsmYkdnyrY0AvoFqU5AssmsflbfLHkcvIHtCri6Cwfm2/eGoZmssP20eEnWihtdbCeA/r0E4bq6o3H0MtS+tppzzXgsig96S2Ht6ux6Xogx3NXAlyk/bnocnks/9zVZTN8LNd4O+x37FnRhMw7j8RJcITZqHoNW1DD4dcyQZ8FctGese8WcJAsHi2ldaAUyQkO0VMUAtRDQgsb3L1LtqzLb4j3285Y/47nQFvPM4ZrD5GTt675dIQyzIghir/r6xbTrjdTL431cBzGKgJTtC+ik/lbHQy4+LEWN8I4wbU0XvxFflyTMquFUwwhmL+BuGPt2pXCyXqyslDJ6sdADv0aEp2hL9t5+hRwTQE9vdupnbjia2kl6Wo0QZeo61uCek8e0ynxKabnQUroUImU5bnu7Xb7bGKjVM5txvPAwVAlybjbZT0rdhOvl2vykjHOaVkpBwKGKgIqvU8PXk7AtD4kwlZDTWAywVbGJ/0gsRtfqwVlvJbS8ZiU=
    on_success: always
